title: DapTap
buildFuture: true
defaultContentLanguage: en
languageCode: en
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: "Panel "
      category: "GAME SERVERS "
      description: This is the Game Server Panel where you can mange Game services
      partial: TEST
    - name: BACKEND
      category: "GAME SERVERS "
    - name: "APIs "
      category: "GAME SERVERS "
    - name: Website Frontend
      category: "WEBSITE "
    - name: Website Backend
      category: "WEBSITE "
    - name: VPS
      category: "DapTap CA server "
    - name: VPS panel
      category: "DapTap CA server "
    - name: MAIN
      category: "DapTap CA server "
    - name: API
      category: "DapTap CA server "
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/6cc66739-39cc-4e07-b715-980d21eeb051.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: "GAME SERVERS "
    - name: "WEBSITE "
    - name: "DapTap CA server "
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
baseURL: dt
